// <auto-generated />
using System;
using CNPM_DeMo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CNPM_DeMo.Migrations
{
    [DbContext(typeof(LibManageDbContext))]
    partial class LibManageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CNPM_DeMo.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhauMaHoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HoTen = "Quản trị viên",
                            IsActive = true,
                            MatKhauMaHoa = "Admin@123",
                            TenDangNhap = "admin",
                            VaiTro = 0
                        });
                });

            modelBuilder.Entity("CNPM_DeMo.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<string>("NhaXuatBan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TacGia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaSach")
                        .IsUnique();

                    b.ToTable("Books");
                });

            modelBuilder.Entity("CNPM_DeMo.Models.BorrowDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("BorrowTicketId")
                        .HasColumnType("int");

                    b.Property<bool>("DaTra")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayTraThucTe")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienPhatHuHai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienPhatQuaHan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TinhTrangKhiTra")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("BorrowTicketId");

                    b.ToTable("BorrowDetails");
                });

            modelBuilder.Entity("CNPM_DeMo.Models.BorrowTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaPhieu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayPhaiTra")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReaderCardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaPhieu")
                        .IsUnique();

                    b.HasIndex("ReaderCardId");

                    b.ToTable("BorrowTickets");
                });

            modelBuilder.Entity("CNPM_DeMo.Models.ReaderCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaThe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("MaThe")
                        .IsUnique();

                    b.ToTable("ReaderCards");
                });

            modelBuilder.Entity("CNPM_DeMo.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoTuoiToiDa")
                        .HasColumnType("int");

                    b.Property<int>("DoTuoiToiThieu")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGiaPhatNgay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoSachMuonToiDa")
                        .HasColumnType("int");

                    b.Property<int>("ThoiHanMuonNgay")
                        .HasColumnType("int");

                    b.Property<int>("ThoiHanTheThang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoTuoiToiDa = 60,
                            DoTuoiToiThieu = 18,
                            DonGiaPhatNgay = 1000m,
                            SoSachMuonToiDa = 5,
                            ThoiHanMuonNgay = 14,
                            ThoiHanTheThang = 6
                        });
                });

            modelBuilder.Entity("CNPM_DeMo.Models.BorrowDetail", b =>
                {
                    b.HasOne("CNPM_DeMo.Models.Book", "Book")
                        .WithMany("BorrowDetails")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CNPM_DeMo.Models.BorrowTicket", "BorrowTicket")
                        .WithMany("BorrowDetails")
                        .HasForeignKey("BorrowTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BorrowTicket");
                });

            modelBuilder.Entity("CNPM_DeMo.Models.BorrowTicket", b =>
                {
                    b.HasOne("CNPM_DeMo.Models.ReaderCard", "ReaderCard")
                        .WithMany("BorrowTickets")
                        .HasForeignKey("ReaderCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReaderCard");
                });

            modelBuilder.Entity("CNPM_DeMo.Models.Book", b =>
                {
                    b.Navigation("BorrowDetails");
                });

            modelBuilder.Entity("CNPM_DeMo.Models.BorrowTicket", b =>
                {
                    b.Navigation("BorrowDetails");
                });

            modelBuilder.Entity("CNPM_DeMo.Models.ReaderCard", b =>
                {
                    b.Navigation("BorrowTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
